export const PROJECT_ACTIONS = {
  SET_ALL_PROJECTS: 'SET_ALL_PROJECTS_ACTION',
  UNSET_ALL_PROJECTS: 'UNSET_ALL_PROJECTS_ACTION',
  FETCH_ALL_PROJECTS: 'FETCH_ALL_PROJECTS_ACTION',
  FETCH_ADD_PROJECT: 'FETCH_ADD_PROJECT_ACTION',
  FETCH_EDIT_PROJECT: 'FETCH_EDIT_PROJECT_ACTION',
  FETCH_DELETE_PROJECT: 'FETCH_DELETE_PROJECT_ACTION',
  REQUEST_START: 'REQUEST_START_PROJECT_ACTION',
  REQUEST_DONE: 'REQUEST_DONE_PROJECT_ACTION',
};


