export const REMINDER_ACTIONS = {
    SET_ALL_REMINDERS: 'SET_ALL_REMINDERS_ACTION',
    UNSET_ALL_REMINDERS: 'UNSET_ALL_REMINDERS_ACTION',
    FETCH_ALL_REMINDERS: 'FETCH_ALL_REMINDERS_ACTION',
    FETCH_ADD_REMINDER: 'FETCH_ADD_REMINDER_ACTION',
    FETCH_EDIT_REMINDER: 'FETCH_EDIT_REMINDER_ACTION',
    FETCH_DELETE_REMINDER: 'FETCH_DELETE_REMINDER_ACTION',
    REQUEST_START: 'REQUEST_START_REMINDER_ACTION',
    REQUEST_DONE: 'REQUEST_DONE_REMINDER_ACTION',
  };
  
