export const TECHNOLOGY_ACTIONS = {
  SET_ALL_TECHNOLOGIES: 'SET_ALL_TECHNOLOGIES_ACTION',
  UNSET_ALL_TECHNOLOGIES: 'UNSET_ALL_TECHNOLOGIES_ACTION',
  FETCH_ALL_TECHNOLOGIES: 'FETCH_ALL_TECHNOLOGIES_ACTION',
  FETCH_ADD_TECHNOLOGY: 'FETCH_ADD_TECHNOLOGY_ACTION',
  FETCH_EDIT_TECHNOLOGY: 'FETCH_EDIT_TECHNOLOGY_ACTION',
  FETCH_DELETE_TECHNOLOGY: 'FETCH_DELETE_TECHNOLOGY_ACTION',
  REQUEST_START: 'REQUEST_START_TECHNOLOGY_ACTION',
  REQUEST_DONE: 'REQUEST_DONE_TECHNOLOGY_ACTION',
};

